name: Test

on: [pull_request]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chisel3-tools
      options: --user github --entrypoint /bin/bash
    env:
      CHISEL3_REF: master
      FIRRTL_REF: master
      FIRRTL_INTERPRETER_REF: master
      TREADLE_REF: master

    steps:
      - name: id
        run: |
          uid=$(id -u)
          echo ::set-env name=CONTAINER_HOME::$(if [ "$uid" = "0" ]; then echo "/root"; else echo "/home/github"; fi)
          printenv
          whoami
          git --version
          pwd
          echo ls -la $HOME .
          ls -la $HOME .
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: repo
      - name: cache-sbt
        uses: actions/cache@v1
        env:
          cache-name: cache-sbt
        with:
          path: ~/.sbt
          key: build-${{ env.cache-name }}-v1-${{ hashFiles('repo/build.sbt') }}-${{hashFiles('repo/project/*')}}
          restore-keys: |
            -build-${{ env.cache-name }}-v1-
            -build-${{ env.cache-name }}-
      - name: cache-coursier
        uses: actions/cache@v1
        env:
          cache-name: cache-coursier
        with:
          path: ~/.cache
          key: build-${{ env.cache-name }}-v1-${{ hashFiles('repo/build.sbt') }}-${{ hashFiles('repo/project/*') }}
          restore-keys: |
            -build-${{ env.cache-name }}-v1-
            -build-${{ env.cache-name }}-
      - name: list
        id: list
        run: |
          echo ls -la . repo ~/.sbt ~/.cache /home/github /home/github/.??*
          ls -la . repo repo/.github/scripts ~/.sbt ~/.cache /home/github /home/github/.??*
      - name: env
        id: env
        run: |
          echo "cat $GITHUB_EVENT_PATH"
          cat $GITHUB_EVENT_PATH
      - name: gawk
        id: gawk
        run: |
          gawk -f repo/.github/scripts/ExtractBuildDependenciesFromPullRequest.gawk $GITHUB_EVENT_PATH > deps
          ls -l deps
          cat deps
      - name: clone-deps
        id: clone-deps
        run: |
          export SBT_OPTS="-d -v $SBT_OPTS"
          gawk -f repo/.github/scripts/generateGitClones.gawk deps > clones
          cat clones
          bash clones
      - name: version-deps
        id: version-deps
        run: |
          versionDeps=$(gawk -f repo/.github/scripts/generateVersionOverrides.gawk deps)
          echo "sbt $versionDeps"
      - name: result
        id: result
        run: |
          ls -la ~ ~/.sbt ~/.cache /home/github /home/github/.??*
